apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service
  namespace: deploy-status-checker
  labels:
    app: deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-service
  template:
    metadata:
      labels:
        app: deploy-service
    spec:
      containers:
        - name: deploy-service
          image: deploy-status-checker/deploy-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: deploy-service-cm
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: deploy-service-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
